### ISSUE TITLE
Is NCache Express the same as NCache Open Source?

### ISSUE THREAD

**Issue by ccrandall69** [Alachisoft/NCache#6]
We are running a somewhat old version of NCache, 4.3.0.  The installer says it's NCache Express and it was thought that this version would only run on 2 servers.  However, I cannot find any information on NCache Express and was wondering if anyone knew if it was basically the same as NCache Open Source?

We are trying to install a cluster on 3 servers and we are getting all sorts of errors with one of the servers.... either the cluster won't install/start on the third server or it will start but say there's only 1 member in the cluster while the other 2 servers show 2 members.

Unfortunately, the person who brought this product into our enterprise has long since left and no one here knows anything about it.  I'm would like to just get NCache 4.4 or higher Open Source and use that, but it will require a full set of regression testing that we do not have resources for at that moment.

Thanks!

**Comment by basitanwer** [comment]
I think NCahce Express has been replaced by NCache Open Source (4.4) and the last Express version was something like 3.4 (not 4.3 as far as i remember).

And since there is a version difference, Express and OSS are not the same. The OSS is more feature-rich and more stable in comparison.

Lastly, Express, i think, did have a limitation on the number of servers whereas the OSS NCache doesn't have any limitations on the number of servers at all.

I strongly suggest you to adopt the Open Source NCache. In case of bugs, the community might be able to help you more.

PS: What's the error you're getting?

**Comment by ccrandall69** [comment]
Thank you for the response.  I also pinged support at Alachisoft and they did confirm that Express != Open Source and was limited to 2 servers.  So we are moving to the open source edition now.  However, the key I received for it is not working.  I'll post separately about that.

**Comment by basitanwer** [comment]
Awesome! Good to hear i could be of help
